version: "3.1"
services:
  server:
    image: python:3.6.4
    ports:
      - "5000:5000"
    hostname: server
    container_name: server
    volumes:
      - ./:/app
    tty: true
    command: bash -c "cd /app && pip3 install -r ./requirements.txt && sh setup.sh"
